####     COMPOSE DE DESARROLLO   #####
services:
  caddy:
    container_name: caddy
    build: ./deployment
    ports:
      - 8443:443 # MAIN PORT TO ACCESS TO FRONTEND AND EVERYTHING
    volumes:
      - ./deployment:/etc/caddy/
      - be_media:/app/media
    restart: always
    depends_on:
      - be
      - fe
      - prometheus
      - grafana
    networks:
      - transcendence_network

  be:
    container_name: be
    build: ./be
    # ports:
    #   - 8000:8000
    volumes:
      - ./be:/app
      - be_media:/app/media
    env_file:
      - ${TRANSCENDENCE_ENV_FILE:-.env}
    restart: always
    depends_on:
      - db
    networks:
      - transcendence_network

  db:
    container_name: db
    image: postgres
    # ports:
    #   - 5432:5432
    env_file:
      - ${TRANSCENDENCE_ENV_FILE:-.env}
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - transcendence_network

  fe:
    container_name: fe
    build: ./fe
    ports:
      - 3002:3002
    volumes:
      - ./fe:/app
      - /app/node_modules
    networks:
      - transcendence_network

  # añadido para monitorizacion
  prometheus:
    container_name: prom
    build: ./monitoring
    user: prometheus
    command:
    - '--web.external-url=https://localhost:8443/prometheus/'
    - '--web.route-prefix=/'
    - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    depends_on:
      - be
    volumes:
      - prometheus_data:/prometheus
    networks:
      - transcendence_network

  grafana:
    container_name: grf
    build: ./monitoring/grafana-config
    user: grafana
    env_file:
      - ${TRANSCENDENCE_ENV_FILE:-.env}
    restart: always
    depends_on:
      - prometheus
    networks:
      - transcendence_network

  postgres_exporter:
    container_name: pg_exporter
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    env_file:
      - ${TRANSCENDENCE_ENV_FILE:-.env}
    command: '--no-collector.stat_bgwriter'
    restart: always
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - transcendence_network

  blackbox_exporter:
    container_name: blackbox
    build: ./monitoring/blackbox
    ports:
      - 9115:9115
    restart: always
    env_file:
      - ${TRANSCENDENCE_ENV_FILE:-.env}
    networks:
      - transcendence_network


volumes:
  db_data:
  grafana_data:
  prometheus_data:
  be_media:


networks:
  transcendence_network:
    driver: bridge
