global:
  scrape_interval: 3s
  # scrape_interval: 15s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'backend'
    static_configs:
      - targets: ['be:8000']

