name: Auto-fix Code Style

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker compose build

  frontend:
    runs-on: ubuntu-latest
    needs: build
    env:
      TRANSCENDENCE_ENV_FILE: ./fe/.env_example
    steps:
      - uses: actions/checkout@v4

      - name: Install frontend dependencies
        run: docker compose run --rm fe npm install

      - name: Fix frontend style
        run: docker compose run --rm fe npm run fix

  backend-black-format:
    runs-on: ubuntu-latest
    needs: build
    env:
      TRANSCENDENCE_ENV_FILE: ./be/.env_example
    steps:
      - uses: actions/checkout@v4

      - name: Format backend with Black
        run: docker compose run --rm be black .

  backend-flake8-check:
    runs-on: ubuntu-latest
    needs: build
    env:
      TRANSCENDENCE_ENV_FILE: ./be/.env_example
    steps:
      - uses: actions/checkout@v4

      - name: Check with Flake8
        run: docker compose run --rm be flake8 .

  commit-changes:
    runs-on: ubuntu-latest
    needs: [frontend, backend-black-format, backend-flake8-check]
    steps:
      - uses: actions/checkout@v4

      - name: Commit fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format/check code"
          branch: ${{ github.ref }}